//! Library backing the `hl-cli` binary, kept separate from `main.rs` so
//! the CLI's actual logic is testable and growable (more subcommands and
//! options are expected once the parser/codegen stages exist) independent
//! of process-level concerns like `std::env::args` and exit codes.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use clap::Parser;
use hl_lexer::Lexer;

/// The header `--build` puts at the top of every Compose document it
/// produces, whether written to a file or printed to stdout.
///
/// It exists to make generated output self-identifying — in a repo, in a
/// diff, in review — and, more concretely, so `hllc` can tell its own
/// output apart from a hand-written `docker-compose.yml` before
/// overwriting one (#85). YAML comments are inert to Compose itself, so
/// carrying it costs nothing at deploy time.
pub const GENERATED_HEADER: &str = "\
# Generated by hllc — do not edit.
# Edit the .hll source and re-run `hllc --build` instead.
";

/// The prefix of [`GENERATED_HEADER`] that marks a file as generated.
///
/// Recognition deliberately keys off only this leading fragment rather
/// than the whole header: the wording after it (and anything a later
/// version might add, e.g. a version stamp) can change without every
/// file written by an older `hllc` suddenly looking hand-written.
const GENERATED_MARKER: &str = "# Generated by hllc";

/// The examples/field-reference block appended after clap's own
/// auto-generated usage/options text (#88) — someone who downloaded the
/// binary with one Compose service to convert has something to copy
/// immediately, rather than only prose about each flag's implementation.
const AFTER_HELP: &str = "\
EXAMPLES:
    hllc --build jellyfin.hll                          Print Compose YAML to stdout
    hllc --build jellyfin.hll --out docker-compose.yml  Write it to a file
    hllc --build services/                              Build every service in a directory

See the book for the full field reference and directory-build modes:
https://travisboettcher.github.io/hl-lang/";

/// Lex, parse (`--parse`), or build Compose YAML (`--build`) from an
/// hl-lang (`.hll`) source file or, in `--build`'s case, a directory of
/// them.
#[derive(Debug, Parser)]
#[command(name = "hllc", version, about, after_help = AFTER_HELP)]
pub struct Cli {
    /// Path to an .hll source file, or (with `--build`) a directory of them.
    pub file: PathBuf,
    /// Parse the file and pretty-print its AST instead of just lexing.
    #[arg(long, conflicts_with = "build")]
    pub parse: bool,
    /// Compile the file (or every `.hll` file directly inside the
    /// directory) into Compose YAML: parse, resolve template/`with`
    /// composition, then generate. One input file always produces one
    /// output document (it may hold multiple services).
    #[arg(long)]
    pub build: bool,
    /// Where to write `--build`'s output. For a single input file,
    /// omitting this prints the YAML to stdout; for a directory input,
    /// this is required (each input file's stem becomes
    /// `<out>/<stem>/docker-compose.yml`).
    #[arg(long, requires = "build")]
    pub out: Option<PathBuf>,
    /// Overwrite existing output files even when they don't carry
    /// `hllc`'s generated header — i.e. files `hllc` didn't write.
    /// Applies to `--build` only.
    #[arg(long, requires = "build")]
    pub force: bool,
}

/// Runs the CLI for an already-parsed [`Cli`] invocation.
pub fn run(cli: Cli) -> ExitCode {
    if cli.build {
        return run_build(&cli.file, cli.out.as_deref(), cli.force);
    }

    let path = &cli.file;

    let source = match fs::read_to_string(path) {
        Ok(source) => source,
        Err(err) => {
            eprintln!("{}: {err}", path.display());
            return ExitCode::FAILURE;
        }
    };

    if cli.parse {
        return match hl_parser::parse(&source) {
            Ok(program) => match write_stdout(&format!("{program:#?}\n")) {
                Ok(()) => ExitCode::SUCCESS,
                Err(code) => code,
            },
            Err(err) => {
                eprintln!("{}: {err}", path.display());
                ExitCode::FAILURE
            }
        };
    }

    for result in Lexer::new(&source) {
        match result {
            Ok(token) => {
                let line = format!(
                    "{}:{} {:?} {:?}\n",
                    token.span.line, token.span.col, token.kind, token.lexeme
                );
                if let Err(code) = write_stdout(&line) {
                    return code;
                }
            }
            Err(err) => {
                eprintln!("{}:{err}", path.display());
                return ExitCode::FAILURE;
            }
        }
    }

    ExitCode::SUCCESS
}

fn run_build(path: &Path, out: Option<&Path>, force: bool) -> ExitCode {
    let is_dir = match fs::metadata(path) {
        Ok(meta) => meta.is_dir(),
        Err(err) => {
            eprintln!("{}: {err}", path.display());
            return ExitCode::FAILURE;
        }
    };

    if is_dir {
        let (hll_files, subdirs) = match scan_dir(path) {
            Ok(scanned) => scanned,
            Err(code) => return code,
        };

        // A directory holding `.hll` files directly is the flat case:
        // one independent entry point per file, `--out` required (there's
        // no single meaningful default location for potentially many
        // files' output). A directory holding no `.hll` files of its own
        // is the co-located case (#12): recurse through its
        // subdirectories looking for service directories, however many
        // levels down they sit (#89) — a root whose immediate children
        // are library/intermediate directories (a `shared/` directory of
        // templates, or a `services/` directory that itself holds no
        // `.hll` files but nests every real service directory one level
        // further) is a common real layout, not a malformed one.
        if !hll_files.is_empty() {
            return build_flat_directory(&hll_files, path, out, force);
        }
        let mut built = 0usize;
        for subdir in &subdirs {
            if let Err(code) = build_colocated_tree(subdir, path, out, force, 0, &mut built) {
                return code;
            }
        }
        if built == 0 {
            eprintln!(
                "{}: no service directories found (looked for a single .hll \
                 file declaring a `service`, in this directory or any \
                 subdirectory) — nothing was built",
                path.display()
            );
        }
        return ExitCode::SUCCESS;
    }

    let yaml = match build_yaml(path) {
        Ok(yaml) => yaml,
        Err(code) => return code,
    };
    match out {
        Some(out_path) => {
            // An existing directory named as `--out` writes
            // `docker-compose.yml` inside it, matching directory mode's
            // own convention. `dist/` is the natural first guess for
            // `--out` — every directory-build example in the book uses
            // exactly this shape — and previously failed with a bare
            // `Is a directory (os error 21)` (#88).
            let out_path = if out_path.is_dir() {
                out_path.join("docker-compose.yml")
            } else {
                out_path.to_path_buf()
            };
            let out_path = out_path.as_path();
            if let Some(parent) = out_path.parent()
                && !parent.as_os_str().is_empty()
                && let Err(err) = fs::create_dir_all(parent)
            {
                eprintln!("{}: {err}", parent.display());
                return ExitCode::FAILURE;
            }
            if let Err(code) = write_output(out_path, &yaml, force) {
                return code;
            }
            if let Err(code) = write_stdout(&format!("{}\n", out_path.display())) {
                return code;
            }
        }
        None => {
            if let Err(code) = write_stdout(&yaml) {
                return code;
            }
        }
    }
    ExitCode::SUCCESS
}

/// Lists `dir`'s immediate children, split into `.hll` files and
/// subdirectories (both sorted, for deterministic build order).
fn scan_dir(dir: &Path) -> Result<(Vec<PathBuf>, Vec<PathBuf>), ExitCode> {
    let entries = fs::read_dir(dir).map_err(|err| {
        eprintln!("{}: {err}", dir.display());
        ExitCode::FAILURE
    })?;
    let mut hll_files = Vec::new();
    let mut subdirs = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|err| {
            eprintln!("{}: {err}", dir.display());
            ExitCode::FAILURE
        })?;
        let entry_path = entry.path();
        if entry_path.extension().is_some_and(|ext| ext == "hll") {
            hll_files.push(entry_path);
        } else if entry_path.is_dir() {
            subdirs.push(entry_path);
        }
    }
    hll_files.sort();
    subdirs.sort();
    Ok((hll_files, subdirs))
}

/// The flat case: every `.hll` file directly inside `dir` that declares
/// a `service` is its own independent entry point, written to
/// `<out>/<stem>/docker-compose.yml`. A file that declares no service —
/// a library file of templates/networks only — is skipped rather than
/// compiled into its own, service-less Compose document (#89): before
/// this, pointing `--build` at a library directory produced one useless
/// `docker-compose.yml` per file (`services: {}`, every declaration
/// dropped, since codegen only ever emits what a service references).
fn build_flat_directory(
    hll_files: &[PathBuf],
    dir: &Path,
    out: Option<&Path>,
    force: bool,
) -> ExitCode {
    let Some(out_dir) = out else {
        eprintln!(
            "{}: --out <dir> is required when building a directory of .hll files",
            dir.display()
        );
        return ExitCode::FAILURE;
    };
    let mut built = 0usize;
    for hll_path in hll_files {
        match declares_a_service(hll_path) {
            Ok(true) => {}
            Ok(false) => continue,
            Err(code) => return code,
        }
        let Some(stem) = hll_path.file_stem().and_then(|s| s.to_str()) else {
            eprintln!("{}: couldn't determine a file stem", hll_path.display());
            return ExitCode::FAILURE;
        };
        // `file_stem` is purely lexical and has no notion of a *usable*
        // directory name: a file literally called `...hll` yields the
        // stem `..`, and `out_dir.join("..")` resolves one level above
        // `--out`, writing output outside the directory the user chose
        // (#64). Anything that isn't a plain single path component is
        // rejected rather than normalized — there's no sensible output
        // directory such a name could mean.
        if stem.is_empty() || stem == "." || stem == ".." || stem.contains(std::path::is_separator)
        {
            eprintln!(
                "{}: `{stem}` isn't usable as an output directory name",
                hll_path.display()
            );
            return ExitCode::FAILURE;
        }
        if let Err(code) = build_one(hll_path, &out_dir.join(stem), force) {
            return code;
        }
        built += 1;
    }
    if built == 0 {
        eprintln!(
            "{}: none of the .hll files here declare a service — nothing was built",
            dir.display()
        );
    }
    ExitCode::SUCCESS
}

/// How many directory levels [`build_colocated_tree`] will recurse
/// below the build root before giving up. Purely a defensive cap
/// against a symlinked-directory cycle turning the walk into an
/// infinite loop (`fs::read_dir`/`Path::is_dir` both follow symlinks,
/// and nothing else here bounds recursion) — any real homelab tree is a
/// handful of levels deep at most.
const MAX_COLOCATED_DEPTH: usize = 64;

/// The co-located case (#12, #89): recursively walks `dir` (starting
/// from one of the build root's immediate children) looking for service
/// directories — a directory holding exactly one `.hll` file that
/// declares a `service`, co-located with its own `docker-compose.yml`
/// (a real layout — see docs/DESIGN.md's Pipeline section — where each
/// service's `.hll` source sits next to its other files, e.g. `.env`,
/// bind-mounted config, instead of every `.hll` file living in one flat
/// directory).
///
/// A directory that declares no service directly — whether it holds no
/// `.hll` files at all, or holds one or more that declare only
/// templates/networks (a *library* directory like `shared/`) — isn't a
/// service directory itself, so this recurses into its subdirectories
/// instead of erroring on file count. That's what makes a layout like
/// `homelab/services/<service>/<service>.hll`, with an intervening
/// `services/` directory that holds no `.hll` files of its own, resolve
/// correctly: the old one-level-only scan saw `services/` as empty and
/// silently built nothing.
///
/// Each service directory found builds in place (writing right back into
/// that same directory) by default, or under `<out>/<path-from-root>/`
/// if `--out` is given — preserving the tree's own relative structure,
/// the same way flat mode's `--out` remaps by file stem.
fn build_colocated_tree(
    dir: &Path,
    root: &Path,
    out: Option<&Path>,
    force: bool,
    depth: usize,
    built: &mut usize,
) -> Result<(), ExitCode> {
    if depth >= MAX_COLOCATED_DEPTH {
        eprintln!(
            "{}: too many nested directories (over {MAX_COLOCATED_DEPTH} levels below {}) \
             — refusing to recurse further, in case a symlink cycle is involved",
            dir.display(),
            root.display()
        );
        return Err(ExitCode::FAILURE);
    }

    let (hll_files, subdirs) = scan_dir(dir)?;

    let mut service_files = Vec::new();
    for hll_path in &hll_files {
        if declares_a_service(hll_path)? {
            service_files.push(hll_path.clone());
        }
    }

    match service_files.as_slice() {
        [] => {
            for subdir in &subdirs {
                build_colocated_tree(subdir, root, out, force, depth + 1, built)?;
            }
            Ok(())
        }
        [hll_path] => {
            let target_dir = match out {
                Some(out_root) => out_root.join(dir.strip_prefix(root).unwrap_or(dir)),
                None => dir.to_path_buf(),
            };
            build_one(hll_path, &target_dir, force)?;
            *built += 1;
            Ok(())
        }
        _ => {
            eprintln!(
                "{}: {} .hll files here declare a service, expected exactly one \
                 entry point per co-located service directory",
                dir.display(),
                service_files.len()
            );
            Err(ExitCode::FAILURE)
        }
    }
}

/// Whether `hll_path` declares at least one top-level `service` — the
/// same test the linker itself effectively applies: only the *entry*
/// file's own `service` decls are ever used (an imported file's are
/// parsed but discarded, per `hl-linker`'s `graph::build`). A file with
/// none is a library file (templates/networks only), not a buildable
/// entry point (#89).
fn declares_a_service(hll_path: &Path) -> Result<bool, ExitCode> {
    let source = fs::read_to_string(hll_path).map_err(|err| {
        eprintln!("{}: {err}", hll_path.display());
        ExitCode::FAILURE
    })?;
    let program = hl_parser::parse(&source).map_err(|err| {
        eprintln!("{}: {err}", hll_path.display());
        ExitCode::FAILURE
    })?;
    Ok(program
        .decls
        .iter()
        .any(|decl| matches!(decl, hl_parser::TopDecl::Service(_))))
}

/// Builds `hll_path`, writing the result to `target_dir/docker-compose.yml`
/// (creating `target_dir` if needed). Shared by both directory-scan
/// modes' per-entry-point loop.
fn build_one(hll_path: &Path, target_dir: &Path, force: bool) -> Result<(), ExitCode> {
    let yaml = build_yaml(hll_path)?;
    fs::create_dir_all(target_dir).map_err(|err| {
        eprintln!("{}: {err}", target_dir.display());
        ExitCode::FAILURE
    })?;
    let out_path = target_dir.join("docker-compose.yml");
    write_output(&out_path, &yaml, force)?;
    write_stdout(&format!("{}\n", out_path.display()))?;
    Ok(())
}

/// Writes `s` to stdout, exiting cleanly instead of panicking on a
/// closed pipe. `println!`/`print!` call `.expect()` on every write, so
/// piping `--parse`'s (often thousands-of-lines) AST dump into `head` or
/// `less` — the only practical way to read one — hands the user a Rust
/// panic and backtrace the moment the reader closes its end (#88): the
/// pipe closing early is a routine, expected condition, not a failure.
fn write_stdout(s: &str) -> Result<(), ExitCode> {
    use std::io::Write;
    match std::io::stdout().write_all(s.as_bytes()) {
        Ok(()) => Ok(()),
        Err(err) if err.kind() == std::io::ErrorKind::BrokenPipe => Err(ExitCode::SUCCESS),
        Err(err) => {
            eprintln!("{err}");
            Err(ExitCode::FAILURE)
        }
    }
}

/// Writes `yaml` to `out_path`, refusing to do so if `out_path` is a
/// symlink, or (unless `force`) if it's an existing file `hllc` didn't
/// generate.
///
/// `fs::write` follows symlinks, so without the first check a
/// `docker-compose.yml` replaced by a link to some unrelated file would
/// have *that* file truncated and overwritten by a plain
/// `hllc --build <repo>` — the co-located mode in particular writes to
/// paths it discovered by scanning, not paths the user named (#64).
/// Generated output only ever lands on the path it's addressed to;
/// replacing the link itself is left to the user, who can see what it
/// points at.
///
/// `symlink_metadata` is what makes that check meaningful — it reports on
/// the link rather than its target.
///
/// The second check covers the plain-file case (#85): co-located mode
/// discovers `docker-compose.yml` by scanning, so the natural
/// incremental migration — convert one service to `.hll` while the rest
/// stay hand-written Compose — used to silently destroy every
/// hand-tuned file in the tree on the first `hllc --build .`. A file
/// starting with [`GENERATED_MARKER`] is `hllc`'s own previous output
/// and is overwritten as before; anything else is refused until the user
/// says otherwise with `--force`. A file that's there but can't be read
/// back is refused too, rather than assumed safe: whatever is at that
/// path couldn't be inspected, so it can't be shown to be disposable.
///
/// The single `symlink_metadata` call answers both "is it a link?" and
/// "is anything there at all?" — the nothing-there case, which is the
/// normal one, is its `Err` and needs no inspection. `--force` waives
/// only the header check; the symlink refusal holds either way, since a
/// link's whole problem is that the write lands somewhere other than the
/// path in hand, which is not what `--force` is asking for.
fn write_output(out_path: &Path, yaml: &str, force: bool) -> Result<(), ExitCode> {
    match fs::symlink_metadata(out_path) {
        Ok(meta) if meta.file_type().is_symlink() => {
            eprintln!(
                "{}: refusing to write through a symlink",
                out_path.display()
            );
            return Err(ExitCode::FAILURE);
        }
        Ok(_) if !force => match fs::read(out_path) {
            Ok(existing) if existing.starts_with(GENERATED_MARKER.as_bytes()) => {}
            Ok(_) => {
                eprintln!(
                    "{}: refusing to overwrite a file hllc didn't generate \
                     (it has no `{GENERATED_MARKER}` header) — move it aside, \
                     or pass --force to overwrite it",
                    out_path.display()
                );
                return Err(ExitCode::FAILURE);
            }
            Err(err) => {
                eprintln!("{}: {err}", out_path.display());
                return Err(ExitCode::FAILURE);
            }
        },
        _ => {}
    }
    fs::write(out_path, yaml).map_err(|err| {
        eprintln!("{}: {err}", out_path.display());
        ExitCode::FAILURE
    })
}

/// Loads `path`'s whole `use` graph and generates Compose YAML for it,
/// prefixed with [`GENERATED_HEADER`].
///
/// The header is attached here, at the one place every `--build` output
/// passes through, rather than at each write site — so stdout, `--out`,
/// flat mode and co-located mode all carry it, and what a user sees
/// printed is byte-for-byte what a redirect into a file would leave on
/// disk (which `write_output` would then recognize as generated).
///
/// Errors are printed bare (`eprintln!("{err}")`), not wrapped with
/// `path`'s own display like every other error site in this file:
/// `hl_linker::LinkError`'s `Io`/`Parse`/`DuplicateAlias`/`PathEscape`
/// variants already self-prefix with *their own* correct path, which may be an
/// imported file rather than `path` itself, and both `LinkError::Compose`
/// and `hl_codegen::CodegenError` only ever carry a `{line}:{col}`
/// location with no file — accurate for a single file, but a composed
/// service's fields can now originate from any file in the graph, so
/// guessing `path` here would misattribute an error that actually came
/// from an imported template.
fn build_yaml(path: &Path) -> Result<String, ExitCode> {
    let composed = hl_linker::link(path, &hl_linker::FsLoader).map_err(|err| {
        eprintln!("{err}");
        ExitCode::FAILURE
    })?;
    let generated = hl_codegen::generate(composed).map_err(|err| {
        eprintln!("{err}");
        ExitCode::FAILURE
    })?;
    Ok(format!("{GENERATED_HEADER}{}", generated.yaml))
}
