//! Library backing the `hl-cli` binary, kept separate from `main.rs` so
//! the CLI's actual logic is testable and growable (more subcommands and
//! options are expected as the compiler grows) independent of
//! process-level concerns like `std::env::args` and exit codes.
//!
//! # Stability
//!
//! The stable, promised surface of this project is the `hllc` *binary*
//! this crate produces — its subcommands and flags, its exit codes, and
//! what it writes to stdout vs. stderr — together with `.hll` source
//! compatibility and the semantics of the Compose document it
//! generates. That contract is spelled out under "What a version number
//! promises" in the repo README.
//!
//! This crate's Rust API is not part of it. Nothing here is published to
//! crates.io — a release is a git tag plus a GitHub Release carrying the
//! binary (`release-plz.toml`'s `[workspace] publish = false` +
//! `git_only = true`) — and **no semver guarantee applies to these
//! types, fields, or signatures**; they may change in any release,
//! including a patch. Depend on the binary, pinned to a tag, not on the
//! crate.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use clap::{Parser, Subcommand};
use hl_lexer::Lexer;

/// The header `hllc build` puts at the top of every Compose document it
/// produces, whether written to a file or printed to stdout.
///
/// It exists to make generated output self-identifying — in a repo, in a
/// diff, in review — and, more concretely, so `hllc` can tell its own
/// output apart from a hand-written `docker-compose.yml` before
/// overwriting one (#85). YAML comments are inert to Compose itself, so
/// carrying it costs nothing at deploy time.
pub const GENERATED_HEADER: &str = "\
# Generated by hllc—do not edit.
# Edit the .hll source and re-run `hllc build` instead.
";

/// The prefix of [`GENERATED_HEADER`] that marks a file as generated.
///
/// Recognition deliberately keys off only this leading fragment rather
/// than the whole header: the wording after it (and anything a later
/// version might add, e.g. a version stamp) can change without every
/// file written by an older `hllc` suddenly looking hand-written.
const GENERATED_MARKER: &str = "# Generated by hllc";

/// The examples/field-reference block appended after clap's own
/// auto-generated usage/options text (#88) — someone who downloaded the
/// binary with one Compose service to convert has something to copy
/// immediately, rather than only prose about each flag's implementation.
const AFTER_HELP: &str = "\
EXAMPLES:
    hllc build jellyfin.hll                           Print Compose YAML to stdout
    hllc build jellyfin.hll --out docker-compose.yml  Write it to a file
    hllc build services/ --out dist/                  Build every service in a directory
    hllc check services/                              Compile it all, write nothing

See the book for the full field reference and directory-build modes:
https://travisboettcher.github.io/hl-lang/";

/// The `hllc` command line: one subcommand per pipeline depth, each
/// taking one positional path.
///
/// Every mode is a subcommand rather than a flag on a single positional
/// argument (#129). The four modes were always mutually exclusive, and
/// `--out`/`--force` were always meaningless without `--build`, which
/// took a layer of `clap` `conflicts_with`/`requires` validation to
/// enforce; a subcommand can't also be a different subcommand, so those
/// states are structurally unreachable instead of merely rejected.
/// Making `build` say its own name is also what lets bare `hllc` print
/// help rather than dump the lexer's token stream at whoever typed the
/// command for the first time.
///
/// `about` is spelled out rather than taken from this doc comment,
/// which is written for someone reading the source rather than for
/// someone who just typed `hllc`.
#[derive(Debug, Parser)]
#[command(
    name = "hllc",
    version,
    about = "Compile hl-lang (.hll) sources into Docker Compose YAML",
    after_help = AFTER_HELP,
    subcommand_required = true,
    arg_required_else_help = true
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

/// What `hllc` was asked to do. Each variant runs the pipeline to a
/// different depth: `tokens` stops after the lexer, `parse` after the
/// parser, `check` and `build` run all of it — differing only in
/// whether the generated document is written anywhere.
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Compile into Compose YAML.
    ///
    /// Parse, resolve `use` imports and template/`with` composition,
    /// then generate. One input file always produces one output
    /// document (it may hold multiple services).
    Build {
        /// Path to an .hll source file, or a directory of them.
        file: PathBuf,
        /// Where to write the output. For a single input file, omitting
        /// this prints the YAML to stdout; for a directory input, this
        /// is required (each input file's stem becomes
        /// `<out>/<stem>/docker-compose.yml`).
        #[arg(long)]
        out: Option<PathBuf>,
        /// Overwrite existing output files even when they don't carry
        /// `hllc`'s generated header — i.e. files `hllc` didn't write.
        #[arg(long)]
        force: bool,
    },
    /// Run the same pipeline as `build`, writing nothing.
    ///
    /// Exits 0 if every input compiles and non-zero, with a diagnostic
    /// on stderr, if any doesn't. The CI gate: no output path to
    /// invent, and nothing left behind to clean up.
    Check {
        /// Path to an .hll source file, or a directory of them.
        file: PathBuf,
    },
    /// Parse one file and pretty-print its AST.
    ///
    /// A debugging aid: it resolves no imports and no template
    /// composition.
    Parse {
        /// Path to an .hll source file.
        file: PathBuf,
    },
    /// Lex one file and print its token stream.
    ///
    /// A debugging aid for the lexer itself.
    Tokens {
        /// Path to an .hll source file.
        file: PathBuf,
    },
}

/// What a full-pipeline run does with the document it generates —
/// the only thing separating `build` from `check`.
#[derive(Debug, Clone, Copy)]
enum Mode<'a> {
    /// `build`: write the document out (or print it to stdout).
    Build { out: Option<&'a Path>, force: bool },
    /// `check`: drop it on the floor. Compiling it was the point.
    Check,
}

impl<'a> Mode<'a> {
    /// `--out`, or `None` in `check` mode, which writes nothing and so
    /// has no output path to be given one.
    fn out(self) -> Option<&'a Path> {
        match self {
            Mode::Build { out, .. } => out,
            Mode::Check => None,
        }
    }

    /// `--force`, which only `build` can carry: there is nothing to
    /// overwrite when nothing is written.
    fn force(self) -> bool {
        matches!(self, Mode::Build { force: true, .. })
    }

    /// The past participle for this mode's "nothing was ..." message,
    /// so a directory holding no entry point reports what it was asked
    /// to do rather than always saying "built".
    fn past_participle(self) -> &'static str {
        match self {
            Mode::Build { .. } => "built",
            Mode::Check => "checked",
        }
    }
}

/// Runs the CLI for an already-parsed [`Cli`] invocation.
pub fn run(cli: Cli) -> ExitCode {
    match cli.command {
        Command::Build { file, out, force } => run_pipeline(
            &file,
            Mode::Build {
                out: out.as_deref(),
                force,
            },
        ),
        Command::Check { file } => run_pipeline(&file, Mode::Check),
        Command::Parse { file } => run_parse(&file),
        Command::Tokens { file } => run_tokens(&file),
    }
}

/// `hllc parse <file>`: pretty-prints the AST for one file.
fn run_parse(path: &Path) -> ExitCode {
    let source = match fs::read_to_string(path) {
        Ok(source) => source,
        Err(err) => {
            eprintln!("{}: {err}", path.display());
            return ExitCode::FAILURE;
        }
    };
    match hl_parser::parse(&source) {
        Ok(program) => match write_stdout(&format!("{program:#?}\n")) {
            Ok(()) => ExitCode::SUCCESS,
            Err(code) => code,
        },
        Err(err) => {
            eprintln!("{}: {err}", path.display());
            ExitCode::FAILURE
        }
    }
}

/// `hllc tokens <file>`: prints one file's token stream.
fn run_tokens(path: &Path) -> ExitCode {
    let source = match fs::read_to_string(path) {
        Ok(source) => source,
        Err(err) => {
            eprintln!("{}: {err}", path.display());
            return ExitCode::FAILURE;
        }
    };
    for result in Lexer::new(&source) {
        match result {
            Ok(token) => {
                let line = format!(
                    "{}:{} {:?} {:?}\n",
                    token.span.line, token.span.col, token.kind, token.lexeme
                );
                if let Err(code) = write_stdout(&line) {
                    return code;
                }
            }
            Err(err) => {
                eprintln!("{}:{err}", path.display());
                return ExitCode::FAILURE;
            }
        }
    }
    ExitCode::SUCCESS
}

/// `hllc build` and `hllc check`: the full pipeline over one file or a
/// directory of them, with [`Mode`] deciding what happens to each
/// generated document afterwards. Everything up to that point —
/// which directory shape applies, which files are entry points, which
/// diagnostics come out — is identical between the two, which is why
/// `check` is a mode of this function rather than a pipeline of its
/// own that could drift from the one it is meant to gate.
fn run_pipeline(path: &Path, mode: Mode<'_>) -> ExitCode {
    let is_dir = match fs::metadata(path) {
        Ok(meta) => meta.is_dir(),
        Err(err) => {
            eprintln!("{}: {err}", path.display());
            return ExitCode::FAILURE;
        }
    };

    if is_dir {
        let (hll_files, subdirs) = match scan_dir(path) {
            Ok(scanned) => scanned,
            Err(code) => return code,
        };

        // A directory holding `.hll` files directly is the flat case:
        // one independent entry point per file, `--out` required (there's
        // no single meaningful default location for potentially many
        // files' output). A directory holding no `.hll` files of its own
        // is the co-located case (#12): recurse through its
        // subdirectories looking for service directories, however many
        // levels down they sit (#89) — a root whose immediate children
        // are library/intermediate directories (a `shared/` directory of
        // templates, or a `services/` directory that itself holds no
        // `.hll` files but nests every real service directory one level
        // further) is a common real layout, not a malformed one.
        if !hll_files.is_empty() {
            return build_flat_directory(&hll_files, path, mode);
        }
        let mut done = 0usize;
        for subdir in &subdirs {
            if let Err(code) = build_colocated_tree(subdir, path, mode, 0, &mut done) {
                return code;
            }
        }
        if done == 0 {
            eprintln!(
                "{}: no service directories found (looked for a single .hll \
                 file declaring a `service`, in this directory or any \
                 subdirectory) — nothing was {}",
                path.display(),
                mode.past_participle()
            );
        }
        return ExitCode::SUCCESS;
    }

    let yaml = match build_yaml(path) {
        Ok(yaml) => yaml,
        Err(code) => return code,
    };
    let Mode::Build { out, force } = mode else {
        // `check`: the document compiled, which was the whole
        // question. Nothing is written and nothing is printed —
        // silence and exit 0 is what a gate in front of `docker
        // compose up` wants.
        return ExitCode::SUCCESS;
    };
    match out {
        Some(out_path) => {
            // An existing directory named as `--out` writes
            // `docker-compose.yml` inside it, matching directory mode's
            // own convention. `dist/` is the natural first guess for
            // `--out` — every directory-build example in the book uses
            // exactly this shape — and previously failed with a bare
            // `Is a directory (os error 21)` (#88).
            let out_path = if out_path.is_dir() {
                out_path.join("docker-compose.yml")
            } else {
                out_path.to_path_buf()
            };
            let out_path = out_path.as_path();
            if let Some(parent) = out_path.parent()
                && !parent.as_os_str().is_empty()
                && let Err(err) = fs::create_dir_all(parent)
            {
                eprintln!("{}: {err}", parent.display());
                return ExitCode::FAILURE;
            }
            if let Err(code) = write_output(out_path, &yaml, force) {
                return code;
            }
            if let Err(code) = write_stdout(&format!("{}\n", out_path.display())) {
                return code;
            }
        }
        None => {
            if let Err(code) = write_stdout(&yaml) {
                return code;
            }
        }
    }
    ExitCode::SUCCESS
}

/// Lists `dir`'s immediate children, split into `.hll` files and
/// subdirectories (both sorted, for deterministic build order).
fn scan_dir(dir: &Path) -> Result<(Vec<PathBuf>, Vec<PathBuf>), ExitCode> {
    let entries = fs::read_dir(dir).map_err(|err| {
        eprintln!("{}: {err}", dir.display());
        ExitCode::FAILURE
    })?;
    let mut hll_files = Vec::new();
    let mut subdirs = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|err| {
            eprintln!("{}: {err}", dir.display());
            ExitCode::FAILURE
        })?;
        let entry_path = entry.path();
        if entry_path.extension().is_some_and(|ext| ext == "hll") {
            hll_files.push(entry_path);
        } else if entry_path.is_dir() {
            subdirs.push(entry_path);
        }
    }
    hll_files.sort();
    subdirs.sort();
    Ok((hll_files, subdirs))
}

/// The flat case: every `.hll` file directly inside `dir` that declares
/// a `service` is its own independent entry point, written to
/// `<out>/<stem>/docker-compose.yml`. A file that declares no service —
/// a library file of templates/networks only — is skipped rather than
/// compiled into its own, service-less Compose document (#89): before
/// this, pointing `build` at a library directory produced one useless
/// `docker-compose.yml` per file (`services: {}`, every declaration
/// dropped, since codegen only ever emits what a service references).
///
/// `check` walks the same set of entry points and compiles each one,
/// but takes no `--out`: it writes nothing, so there is no output
/// location to require (#129).
fn build_flat_directory(hll_files: &[PathBuf], dir: &Path, mode: Mode<'_>) -> ExitCode {
    let out_dir = mode.out();
    if out_dir.is_none() && matches!(mode, Mode::Build { .. }) {
        eprintln!(
            "{}: --out <dir> is required when building a directory of .hll files",
            dir.display()
        );
        return ExitCode::FAILURE;
    }
    let mut done = 0usize;
    for hll_path in hll_files {
        match declares_a_service(hll_path) {
            Ok(true) => {}
            Ok(false) => continue,
            Err(code) => return code,
        }
        let target_dir = match out_dir {
            Some(out_dir) => {
                let Some(stem) = hll_path.file_stem().and_then(|s| s.to_str()) else {
                    eprintln!("{}: couldn't determine a file stem", hll_path.display());
                    return ExitCode::FAILURE;
                };
                // `file_stem` is purely lexical and has no notion of a
                // *usable* directory name: a file literally called
                // `...hll` yields the stem `..`, and
                // `out_dir.join("..")` resolves one level above
                // `--out`, writing output outside the directory the
                // user chose (#64). Anything that isn't a plain single
                // path component is rejected rather than normalized —
                // there's no sensible output directory such a name
                // could mean.
                if stem.is_empty()
                    || stem == "."
                    || stem == ".."
                    || stem.contains(std::path::is_separator)
                {
                    eprintln!(
                        "{}: `{stem}` isn't usable as an output directory name",
                        hll_path.display()
                    );
                    return ExitCode::FAILURE;
                }
                Some(out_dir.join(stem))
            }
            None => None,
        };
        if let Err(code) = build_one(hll_path, target_dir.as_deref(), mode.force()) {
            return code;
        }
        done += 1;
    }
    if done == 0 {
        eprintln!(
            "{}: none of the .hll files here declare a service — nothing was {}",
            dir.display(),
            mode.past_participle()
        );
    }
    ExitCode::SUCCESS
}

/// How many directory levels [`build_colocated_tree`] will recurse
/// below the build root before giving up. Purely a defensive cap
/// against a symlinked-directory cycle turning the walk into an
/// infinite loop (`fs::read_dir`/`Path::is_dir` both follow symlinks,
/// and nothing else here bounds recursion) — any real homelab tree is a
/// handful of levels deep at most.
const MAX_COLOCATED_DEPTH: usize = 64;

/// The co-located case (#12, #89): recursively walks `dir` (starting
/// from one of the build root's immediate children) looking for service
/// directories — a directory holding exactly one `.hll` file that
/// declares a `service`, co-located with its own `docker-compose.yml`
/// (a real layout — see docs/DESIGN.md's Pipeline section — where each
/// service's `.hll` source sits next to its other files, e.g. `.env`,
/// bind-mounted config, instead of every `.hll` file living in one flat
/// directory).
///
/// A directory that declares no service directly — whether it holds no
/// `.hll` files at all, or holds one or more that declare only
/// templates/networks (a *library* directory like `shared/`) — isn't a
/// service directory itself, so this recurses into its subdirectories
/// instead of erroring on file count. That's what makes a layout like
/// `homelab/services/<service>/<service>.hll`, with an intervening
/// `services/` directory that holds no `.hll` files of its own, resolve
/// correctly: the old one-level-only scan saw `services/` as empty and
/// silently built nothing.
///
/// Each service directory found builds in place (writing right back into
/// that same directory) by default, or under `<out>/<path-from-root>/`
/// if `--out` is given — preserving the tree's own relative structure,
/// the same way flat mode's `--out` remaps by file stem. Under `check`
/// the same walk happens and every entry point is compiled, but nothing
/// is written anywhere, in place or otherwise (#129).
fn build_colocated_tree(
    dir: &Path,
    root: &Path,
    mode: Mode<'_>,
    depth: usize,
    done: &mut usize,
) -> Result<(), ExitCode> {
    if depth >= MAX_COLOCATED_DEPTH {
        eprintln!(
            "{}: too many nested directories (over {MAX_COLOCATED_DEPTH} levels below {}) \
             — refusing to recurse further, in case a symlink cycle is involved",
            dir.display(),
            root.display()
        );
        return Err(ExitCode::FAILURE);
    }

    let (hll_files, subdirs) = scan_dir(dir)?;

    let mut service_files = Vec::new();
    for hll_path in &hll_files {
        if declares_a_service(hll_path)? {
            service_files.push(hll_path.clone());
        }
    }

    match service_files.as_slice() {
        [] => {
            for subdir in &subdirs {
                build_colocated_tree(subdir, root, mode, depth + 1, done)?;
            }
            Ok(())
        }
        [hll_path] => {
            let target_dir = match mode {
                Mode::Check => None,
                Mode::Build {
                    out: Some(out_root),
                    ..
                } => Some(out_root.join(dir.strip_prefix(root).unwrap_or(dir))),
                Mode::Build { out: None, .. } => Some(dir.to_path_buf()),
            };
            build_one(hll_path, target_dir.as_deref(), mode.force())?;
            *done += 1;
            Ok(())
        }
        _ => {
            eprintln!(
                "{}: {} .hll files here declare a service, expected exactly one \
                 entry point per co-located service directory",
                dir.display(),
                service_files.len()
            );
            Err(ExitCode::FAILURE)
        }
    }
}

/// Whether `hll_path` declares at least one top-level `service` — the
/// same test the linker itself effectively applies: only the *entry*
/// file's own `service` decls are ever used (an imported file's are
/// parsed but discarded, per `hl-linker`'s `graph::build`). A file with
/// none is a library file (templates/networks only), not a buildable
/// entry point (#89).
fn declares_a_service(hll_path: &Path) -> Result<bool, ExitCode> {
    let source = fs::read_to_string(hll_path).map_err(|err| {
        eprintln!("{}: {err}", hll_path.display());
        ExitCode::FAILURE
    })?;
    let program = hl_parser::parse(&source).map_err(|err| {
        eprintln!("{}: {err}", hll_path.display());
        ExitCode::FAILURE
    })?;
    Ok(program
        .decls
        .iter()
        .any(|decl| matches!(decl, hl_parser::TopDecl::Service(_))))
}

/// Builds `hll_path`, writing the result to `target_dir/docker-compose.yml`
/// (creating `target_dir` if needed). Shared by both directory-scan
/// modes' per-entry-point loop.
///
/// A `target_dir` of `None` is `check` (#129): the document is
/// generated — which is what raises every diagnostic the gate exists to
/// catch — and then dropped, with nothing created and nothing printed.
fn build_one(hll_path: &Path, target_dir: Option<&Path>, force: bool) -> Result<(), ExitCode> {
    let yaml = build_yaml(hll_path)?;
    let Some(target_dir) = target_dir else {
        return Ok(());
    };
    fs::create_dir_all(target_dir).map_err(|err| {
        eprintln!("{}: {err}", target_dir.display());
        ExitCode::FAILURE
    })?;
    let out_path = target_dir.join("docker-compose.yml");
    write_output(&out_path, &yaml, force)?;
    write_stdout(&format!("{}\n", out_path.display()))?;
    Ok(())
}

/// Writes `s` to stdout, exiting cleanly instead of panicking on a
/// closed pipe. `println!`/`print!` call `.expect()` on every write, so
/// piping `hllc parse`'s (often thousands-of-lines) AST dump into `head` or
/// `less` — the only practical way to read one — hands the user a Rust
/// panic and backtrace the moment the reader closes its end (#88): the
/// pipe closing early is a routine, expected condition, not a failure.
fn write_stdout(s: &str) -> Result<(), ExitCode> {
    use std::io::Write;
    match std::io::stdout().write_all(s.as_bytes()) {
        Ok(()) => Ok(()),
        Err(err) if err.kind() == std::io::ErrorKind::BrokenPipe => Err(ExitCode::SUCCESS),
        Err(err) => {
            eprintln!("{err}");
            Err(ExitCode::FAILURE)
        }
    }
}

/// Writes `yaml` to `out_path`, refusing to do so if `out_path` is a
/// symlink, or (unless `force`) if it's an existing file `hllc` didn't
/// generate.
///
/// `fs::write` follows symlinks, so without the first check a
/// `docker-compose.yml` replaced by a link to some unrelated file would
/// have *that* file truncated and overwritten by a plain
/// `hllc build <repo>` — the co-located mode in particular writes to
/// paths it discovered by scanning, not paths the user named (#64).
/// Generated output only ever lands on the path it's addressed to;
/// replacing the link itself is left to the user, who can see what it
/// points at.
///
/// `symlink_metadata` is what makes that check meaningful — it reports on
/// the link rather than its target.
///
/// The second check covers the plain-file case (#85): co-located mode
/// discovers `docker-compose.yml` by scanning, so the natural
/// incremental migration — convert one service to `.hll` while the rest
/// stay hand-written Compose — used to silently destroy every
/// hand-tuned file in the tree on the first `hllc build .`. A file
/// starting with [`GENERATED_MARKER`] is `hllc`'s own previous output
/// and is overwritten as before; anything else is refused until the user
/// says otherwise with `--force`. A file that's there but can't be read
/// back is refused too, rather than assumed safe: whatever is at that
/// path couldn't be inspected, so it can't be shown to be disposable.
///
/// The single `symlink_metadata` call answers both "is it a link?" and
/// "is anything there at all?" — the nothing-there case, which is the
/// normal one, is its `Err` and needs no inspection. `--force` waives
/// only the header check; the symlink refusal holds either way, since a
/// link's whole problem is that the write lands somewhere other than the
/// path in hand, which is not what `--force` is asking for.
fn write_output(out_path: &Path, yaml: &str, force: bool) -> Result<(), ExitCode> {
    match fs::symlink_metadata(out_path) {
        Ok(meta) if meta.file_type().is_symlink() => {
            eprintln!(
                "{}: refusing to write through a symlink",
                out_path.display()
            );
            return Err(ExitCode::FAILURE);
        }
        Ok(_) if !force => match fs::read(out_path) {
            Ok(existing) if existing.starts_with(GENERATED_MARKER.as_bytes()) => {}
            Ok(_) => {
                eprintln!(
                    "{}: refusing to overwrite a file hllc didn't generate \
                     (it has no `{GENERATED_MARKER}` header) — move it aside, \
                     or pass --force to overwrite it",
                    out_path.display()
                );
                return Err(ExitCode::FAILURE);
            }
            Err(err) => {
                eprintln!("{}: {err}", out_path.display());
                return Err(ExitCode::FAILURE);
            }
        },
        _ => {}
    }
    fs::write(out_path, yaml).map_err(|err| {
        eprintln!("{}: {err}", out_path.display());
        ExitCode::FAILURE
    })
}

/// Loads `path`'s whole `use` graph and generates Compose YAML for it,
/// prefixed with [`GENERATED_HEADER`].
///
/// The header is attached here, at the one place every `build` output
/// passes through, rather than at each write site — so stdout, `--out`,
/// flat mode and co-located mode all carry it, and what a user sees
/// printed is byte-for-byte what a redirect into a file would leave on
/// disk (which `write_output` would then recognize as generated).
///
/// Errors are printed bare (`eprintln!("{err}")`), not wrapped with
/// `path`'s own display like every other error site in this file: every
/// error out of this pipeline names its own file(s) already, and that
/// file may be an imported one rather than `path` itself.
/// `hl_linker::LinkError`'s `Io`/`Parse`/`DuplicateAlias`/`PathEscape`
/// variants carry the path they're about directly, while
/// `LinkError::Compose` and `hl_codegen::CodegenError` resolve each
/// span's own [`hl_parser::FileId`] through the graph's
/// `hl_parser::SourceMap` (#75) — so a composed service's fields report
/// the file each one actually came from, including both sides of a
/// two-location collision error, rather than one guessed path for the
/// lot.
///
/// That map is why the codegen error is rendered through
/// `CodegenError::display`: `generate` consumes the composed program, so
/// the map is cloned out of it first (cheap — a handful of paths).
///
/// Warnings (#80) are rendered the same way and printed to stderr as
/// they come out of each stage, but change nothing else: a build that
/// raises only warnings still writes its output and still exits 0, so
/// `hllc build` stays usable as a CI gate without every dropped
/// declaration failing it. There is no flag to suppress them yet — that
/// is deliberately a separate decision, since a suppression scheme is
/// much harder to retrofit onto one that was designed without it.
fn build_yaml(path: &Path) -> Result<String, ExitCode> {
    let linked = hl_linker::link(path, &hl_linker::FsLoader).map_err(|err| {
        eprintln!("{err}");
        ExitCode::FAILURE
    })?;
    let files = linked.program.files.clone();
    for warning in &linked.warnings {
        eprintln!("{}", warning.display(&files));
    }
    let generated = hl_codegen::generate(linked.program).map_err(|err| {
        eprintln!("{}", err.display(&files));
        ExitCode::FAILURE
    })?;
    for warning in &generated.warnings {
        eprintln!("{}", warning.display(&files));
    }
    Ok(format!("{GENERATED_HEADER}{}", generated.yaml))
}
